### ISSUE TITLE
Clonar Raspberrys

### ISSUE THREAD

**Issue by Pedrovictorrr** [Exostack-STAF/staf-rasp#1]
Necessita clonar os Raspberry da Mata Fresca.

**Comment by leandrohfaa** [comment]
Instalação rasp_6 fil_2 concluido com sucesso. 
Samuel vai começar a clonar para o restante dos sd na segunda feira.

**Comment by leandrohfaa** [comment]
Nova  .img com 17GB instalada com sucesso e funcionando. 
Rasp Melao 2 - filial_id 2 - Rasp_id - 3
Clonagem da .img iniciada amanha termina parte de configuração.

**Comment by leandrohfaa** [comment]
Samuel comprou 3 rasp para configurar pois estavam com problema na rede previsao 13/12
