### ISSUE TITLE
Instalar Raspberry inicial

### ISSUE THREAD

**Issue by Pedrovictorrr** [Exostack-STAF/staf-rasp#2]
Instalar primeiro rasp no Sebastiao da Manga para clonar.

**Comment by leandrohfaa** [comment]
Foi enviado o .img para realizar o processo de instalação do primeiro rasp para iniciar clonagem pela manha e cliente estava enrolado para realizar o processo. 
Tentarei uma nova instalação na segunda. (Parte da tarde)

**Comment by leandrohfaa** [comment]
Clonagem da .img feita em todos os rasp. 
Erro reportado pelo user de "duplicidade ao bater códigos na leitura" 
![Image](https://github.com/user-attachments/assets/11f1638b-1888-46ad-ad0f-692529be7877)
